version: '3.8'

services:
  react:
    container_name: react
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "80:3000"
    stdin_open: true

volumes:
  postgres_data: