version: "3.3"
services:

  frontend:
    image: 'frontenddev:${TAG-latest}'
    container_name: frontend-solodev
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file:
      - .env
    environment:
      - REACT_APP_BASE_URI=http://localhost
    stdin_open: true
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=${PORT}
    ports:
      - "${SOLODEVPORT}:${PORT}"
    networks:
      - default