version: "3.3"
services:

  frontend:
    image: 'frontenddev:${TAG-latest}'
    container_name: frontend-integrated
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file:
      - .env
    environment:
      - REACT_APP_COMPLETE_DOMAIN=http://${DOMAIN}
    ports:
      - "${SOLODEVPORT}:${PORT}"
    stdin_open: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=${PORT}
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

