version: "3.3"
services:
  frontend:
    image: 'frontendprod:${TAG-latest}'
    container_name: frontend-prod
    build:
      context: .
      target: prod
    volumes:
      - /usr/app/node_modules
    env_file:
      - .env
    environment:
      - REACT_APP_BASE_URI=http://localhost
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
        - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=80
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
