version: "3.7"
services:

  frontend:
    image: 'frontenddev'
    container_name: frontend-integrated
    build:
      context: .
      target: dev
    volumes:
      - ./react:/usr/app
      - ${FRONTEND_CUSTOMIZATION_IMAGES_PATH}:/usr/app/public/static/customization
      - /usr/app/node_modules
    environment:
      - REACT_APP_COMPLETE_DOMAIN=http://${DOMAIN}
      - DOMAIN
      - PORT
      - NODE_ENV=development
      - REACT_APP_PRIMARY_COLOR=${PRIMARY_COLOR}
      - REACT_APP_DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE}
      - REACT_APP_ALLOWED_LANGUAGES=${ALLOWED_LANGUAGES}
    stdin_open: true
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=${PORT}
    networks:
      - traefik-public
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

networks:
  traefik-public:
    external: true

